%%%-------------------------------------------------------------------
%%% rebar3_aihtml -- internal data contract.
%%%
%%% Types, records and constants only. Shared by the provider, the scanner,
%%% the naming/checking passes and the migrate command.
%%%-------------------------------------------------------------------
-ifndef(REBAR3_AIHTML_HRL).
-define(REBAR3_AIHTML_HRL, true).

%% First line of every generated file, and the marker the orphan collector
%% uses to decide whether a file in out_dir is ours to delete.
%%
%% The engine tag matters: two engines may share an out_dir, and without it
%% each would see the other's output as an orphan and delete it on every
%% build -- a failure that depends on which provider ran last.
-define(R3A_BANNER_PREFIX, "%% Generated by rebar3_aihtml").
-define(R3A_BANNER_LEGACY, "%% Generated by rebar3_aihtml from ").
-define(R3A_DONT_EDIT, " -- DO NOT EDIT.").

-define(R3A_DEFAULT_VIEWS,   "views").
-define(R3A_DEFAULT_OUT_DIR, "_gen").

%% Per-app normalised options.
%%
%% Paths come in two flavours on purpose: the absolute ones drive file IO, the
%% relative ones are what reaches the generated code. Only the relative form
%% may end up inside a generated .erl, otherwise the output would carry the
%% developer's home directory and CI would produce different bytes.
-record(mopts, {engine        :: module(),      % ai_mustache_engine | ai_jinja_engine
                app_name      :: atom(),
                app_dir       :: file:filename_all(),
                ebin_dir      :: file:filename_all(),
                src_dirs      :: [file:filename_all()],
                views_dir     :: file:filename_all(),   % absolute
                views_rel     :: string(),              % relative to app_dir
                out_dir       :: file:filename_all(),   % absolute
                out_rel       :: string(),              % relative to app_dir
                suffix        :: string(),
                prefix        :: binary(),
                extensions    :: [module()],
                ext_opts      :: map(),
                line_map      :: boolean(),
                wae           :: boolean(),
                %% Exactly the options that can change the generated code, and
                %% nothing else. out_dir/suffix/warnings_as_errors are absent
                %% by design: folding them in would make renaming out_dir
                %% rebuild the world. This map is what feeds both
                %% Engine:source_hash/2 and the generated module's
                %% self-description, so the stamp and the compilation can
                %% never be computed from different options.
                %%
                %% Named for the template engine, not for erlc: it holds
                %% `escape' and `trim_blocks', never `debug_info'.
                engine_opts   :: map()}).

%% One discovered template.
-record(tpl, {abs_path :: file:filename_all(),
              rel_path :: string(),        % relative to app_dir, e.g. views/a.mustache
              name     :: binary(),        % relative to views_dir, no suffix
              module   :: module(),
              out_path :: file:filename_all(),
              source   :: binary(),        % file contents, read once
              stamp    :: binary(),        % ai_mustache_compiler:source_hash/2
              mtime    :: integer()}).

-endif.
