%%%-------------------------------------------------------------------
%%% rebar3_aihtml -- internal data contract.
%%%
%%% Types, records and constants only. Shared by the provider, the scanner,
%%% the naming/checking passes and the migrate command.
%%%-------------------------------------------------------------------
-ifndef(REBAR3_AIHTML_HRL).
-define(REBAR3_AIHTML_HRL, true).

%% First line of every generated file. Also the marker the orphan collector
%% uses to decide whether a file in out_dir is ours to delete.
-define(R3A_BANNER, "%% Generated by rebar3_aihtml from ").
-define(R3A_DONT_EDIT, " -- DO NOT EDIT.").

-define(R3A_DEFAULT_VIEWS,   "views").
-define(R3A_DEFAULT_SUFFIX,  ".mustache").
-define(R3A_DEFAULT_OUT_DIR, "_gen").
-define(R3A_DEFAULT_PREFIX,  "view_").

%% Every key mustache_opts understands. Anything else earns a warning (an
%% error under warnings_as_errors) rather than failing silently.
-define(R3A_KNOWN_KEYS,
        [views, suffix, out_dir, prefix, extensions, ext_opts, line_map,
         warnings_as_errors]).

%% Per-app normalised options.
%%
%% Paths come in two flavours on purpose: the absolute ones drive file IO, the
%% relative ones are what reaches the generated code. Only the relative form
%% may end up inside a generated .erl, otherwise the output would carry the
%% developer's home directory and CI would produce different bytes.
-record(mopts, {app_name      :: atom(),
                app_dir       :: file:filename_all(),
                ebin_dir      :: file:filename_all(),
                src_dirs      :: [file:filename_all()],
                views_dir     :: file:filename_all(),   % absolute
                views_rel     :: string(),              % relative to app_dir
                out_dir       :: file:filename_all(),   % absolute
                out_rel       :: string(),              % relative to app_dir
                suffix        :: string(),
                prefix        :: binary(),
                extensions    :: [module()],
                ext_opts      :: map(),
                line_map      :: boolean(),
                wae           :: boolean(),
                %% Exactly the options that can change the generated code, and
                %% nothing else. out_dir/suffix/warnings_as_errors are absent
                %% by design: folding them in would make renaming out_dir
                %% rebuild the world. This map is what feeds both
                %% ai_mustache_compiler:source_hash/2 and the -mustache_source
                %% attribute, so the stamp and the compilation can never be
                %% computed from different options.
                compiler_opts :: map()}).

%% One discovered template.
-record(tpl, {abs_path :: file:filename_all(),
              rel_path :: string(),        % relative to app_dir, e.g. views/a.mustache
              name     :: binary(),        % relative to views_dir, no suffix
              module   :: module(),
              out_path :: file:filename_all(),
              source   :: binary(),        % file contents, read once
              stamp    :: binary(),        % ai_mustache_compiler:source_hash/2
              mtime    :: integer()}).

-endif.
