%%%-------------------------------------------------------------------
%%% @doc The three cross-template checks.
%%%
%%%   1. module name collisions, within an app and across apps;
%%%   2. a generated module name shadowing a hand written one;
%%%   3. partials that used to exist and no longer do.
%%%
%%% (3) is the only cross-template dependency the plugin tracks at all.
%%% Partials compile to cross-module calls, so editing a partial never
%%% invalidates its callers and no dependency graph is needed. The single
%%% exception is a partial that disappears: the caller's stamp did not change,
%%% so it would be skipped and the dangling call would only surface as a
%%% runtime undef. See designs/05-rebar3-plugin.md 3.2.
%%% @end
%%%-------------------------------------------------------------------
-module(rebar3_aihtml_check).

-include("rebar3_aihtml.hrl").

-export([collisions/2, handwritten/2, cross_app/1,
         stale_partials/2, partials_exist/3]).

%%%===================================================================
%%% 1. Module name collisions
%%%===================================================================

%% @doc Templates that reduce to the same module name.
%%
%% Runs after the scan and before any compilation: with a collision the
%% surviving file depends on compilation order, so nothing may be written
%% until it is resolved.
collisions(Tpls, _Opts) ->
    Groups = group(Tpls),
    lists:foldr(
      fun({Mod, [_, _ | _] = Paths}, Acc) ->
              Sorted = lists:sort(Paths),
              [{P, 0, {module_conflict, Mod, [Q || Q <- Sorted, Q =/= P]}}
               || P <- Sorted] ++ Acc;
         (_, Acc) ->
              Acc
      end, [], Groups).

group(Tpls) ->
    Map = lists:foldl(fun(#tpl{module = M, rel_path = P}, Acc) ->
                              maps:update_with(M, fun(L) -> [P | L] end, [P], Acc)
                      end, #{}, Tpls),
    lists:sort(maps:to_list(Map)).

%%%===================================================================
%%% 2. Collision with a hand written module
%%%===================================================================

%% @doc A generated module name that an .erl outside out_dir already claims.
%%
%% Erlang module names are global; letting the two coexist means whichever
%% rebar3 compiles last wins, which is not a thing to leave to chance.
handwritten(Tpls, #mopts{src_dirs = SrcDirs, out_dir = OutDir}) ->
    Dirs = [D || D <- SrcDirs, not same_dir(D, OutDir)],
    lists:foldr(
      fun(#tpl{module = Mod, rel_path = Rel}, Acc) ->
              Base = atom_to_list(Mod) ++ ".erl",
              case [F || D <- Dirs,
                         F <- filelib:wildcard(filename:join([D, "**", Base])),
                         filelib:is_regular(F)] of
                  []    -> Acc;
                  [H|_] -> [{Rel, 0, {handwritten_conflict, Mod, H}} | Acc]
              end
      end, [], Tpls).

same_dir(A, B) ->
    filename:absname(unicode:characters_to_list(A)) =:=
        filename:absname(unicode:characters_to_list(B)).

%%%===================================================================
%%% 3. Cross-app collisions
%%%===================================================================

%% @doc Modules generated by more than one app in an umbrella.
%%
%% A warning, not an error: it is a real global clash, but the fix is a per
%% app prefix and the user may be mid-refactor. Under warnings_as_errors the
%% caller promotes it.
cross_app(PerApp) ->
    Map = lists:foldl(
            fun({App, Tpls}, Acc) ->
                    lists:foldl(
                      fun(#tpl{module = M}, A) ->
                              maps:update_with(M, fun(L) -> [App | L] end, [App], A)
                      end, Acc, Tpls)
            end, #{}, PerApp),
    [{Mod, lists:usort(Apps)}
     || {Mod, Apps} <- lists:sort(maps:to_list(Map)),
        length(lists:usort(Apps)) > 1].

%%%===================================================================
%%% 4. Partials that vanished
%%%===================================================================

%% @doc Modules whose generated .erl calls a partial that no longer exists.
%%
%% Returns the set of template modules to force a rebuild of. The rebuild is
%% the point: recompiling the caller makes the compiler report the missing
%% partial with the template line number, which is a far better diagnostic
%% than anything this function could produce from the generated file.
%%
%% A generated file that cannot be read back counts as needing a rebuild, in
%% line with the stamp check.
stale_partials(Tpls, _Opts) ->
    Available = sets:from_list([M || #tpl{module = M} <- Tpls], [{version, 2}]),
    lists:foldl(
      fun(#tpl{module = Mod, out_path = Out}, Acc) ->
              case rebar3_aihtml_scan:partials_of(Out) of
                  error      -> Acc;   % no file, or unreadable: already rebuilt
                  {ok, Deps} ->
                      case [D || D <- Deps, not sets:is_element(D, Available)] of
                          []  -> Acc;
                          _   -> sets:add_element(Mod, Acc)
                      end
              end
      end, sets:new([{version, 2}]), Tpls).

%% @doc Check every {{> name}} in a parsed template against the template set.
%%
%% This is the check ai_mustache_ast:resolve_partials/2 would do from the
%% `views' option, done here instead. resolve_partials/2 probes the file
%% system relative to the current working directory, which is the project root
%% and not the app directory, so it is wrong for an umbrella app; and feeding
%% it an absolute views path would stamp the developer's home directory into
%% every generated module. The template set the plugin already scanned answers
%% the same question with neither problem.
partials_exist(Nodes, Available, Rel) ->
    lists:reverse(walk(Nodes, Available, Rel, [])).

walk([], _Avail, _Rel, Acc) ->
    Acc;
walk([{partial, {Line, _}, Name, _} | Rest], Avail, Rel, Acc) when is_binary(Name) ->
    Acc1 = case sets:is_element(Name, Avail) of
               true  -> Acc;
               false -> [{Rel, Line, {partial_not_found, Name}} | Acc]
           end,
    walk(Rest, Avail, Rel, Acc1);
walk([Node | Rest], Avail, Rel, Acc) ->
    walk(Rest, Avail, Rel, walk(body_of(Node), Avail, Rel, Acc)).

body_of({section,  _, _, B})    -> B;
body_of({inverted, _, _, B})    -> B;
body_of({has,      _, _, B, _}) -> B;
body_of({ext,      _, _, _, B}) -> B;
body_of(_)                      -> [].
