#!/usr/bin/env escript
%%! -noshell
%% Writes apps/aihtml/assets/js/types/catalog.d.ts from aihtml_catalog:
%% for every behaviour the server renders (data-ah="<name>") the names of
%% the methods the server may call on it (aihtml_action:call/4, the
%% catalog's `methods'). AH.register checks each controller class against
%% it, so `tsc' fails when a catalogued method is missing in the browser.
%%
%%   escript scripts/gen-ts-catalog.escript           write the file
%%   escript scripts/gen-ts-catalog.escript --check   fail if it is stale
main(Args) ->
    Root = filename:dirname(filename:dirname(filename:absname(escript:script_name()))),
    [code:add_patha(D) || D <- filelib:wildcard(filename:join(Root, "_build/default/lib/*/ebin"))],
    File = filename:join(Root, "apps/aihtml/assets/js/types/catalog.d.ts"),
    New = unicode:characters_to_binary(source()),
    case Args of
        ["--check"] ->
            case file:read_file(File) of
                {ok, New} -> ok;
                _ ->
                    io:format(standard_error, "~s is stale: run escript scripts/gen-ts-catalog.escript~n",
                              [File]),
                    halt(1)
            end;
        [] ->
            ok = filelib:ensure_dir(File),
            ok = file:write_file(File, New)
    end.

source() ->
    Prefabs = aihtml_catalog:prefabs() ++ aihtml_theme:catalog(),
    %% behaviour -> method names, merged over the prefabs sharing it
    ByName = lists:foldl(
               fun(P, Acc) ->
                       case maps:get(behavior, P, undefined) of
                           undefined -> Acc;
                           B ->
                               Ms = [text(maps:get(name, M)) || M <- maps:get(methods, P, [])],
                               maps:update_with(text(B), fun(Old) -> Old ++ Ms end, Ms, Acc)
                       end
               end, #{}, Prefabs),
    ["// Generated by scripts/gen-ts-catalog.escript from aihtml_catalog. Do not edit.\n"
     "//\n"
     "// Every behaviour the server renders (data-ah=\"<name>\") and the methods\n"
     "// the server may call on it (aihtml_action:call/4). AH.register checks a\n"
     "// controller class against it.\n"
     "export interface Behaviours {\n",
     [["  \"", B, "\": ", methods(lists:usort(Ms)), ";\n"] || {B, Ms} <- lists:sort(maps:to_list(ByName))],
     "}\n"].

methods([]) -> "never";
methods(Ms) -> lists:join(" | ", ["\"" ++ M ++ "\"" || M <- Ms]).

text(A) when is_atom(A) -> atom_to_list(A);
text(B) when is_binary(B) -> binary_to_list(B);
text(L) when is_list(L) -> L.
