%% Import every aihtml builder so pages read as markup:
%%
%%   -include_lib("aihtml/include/aihtml.hrl").
%%
%%   'div'([button(<<"Save">>, save, [primary], [])], [<<"p-4">>], []).
%%
%% Leave this header out and call aihtml:button/4 etc. when an imported
%% name would clash with a local function.
%%
%% It also brings in the element records (#ah_button{} ...), see
%% aihtml_records.hrl and designs/05-records.md.
-include("aihtml_records.hrl").

-import(aihtml,
        ['div'/1, 'div'/3, span/1, span/3, p/1, p/3, a/1, a/3,
         h1/1, h1/3, h2/1, h2/3, h3/1, h3/3, h4/1, h4/3,
         ul/1, ul/3, ol/1, ol/3, li/1, li/3, dl/1, dl/3, dt/1, dt/3, dd/1, dd/3,
         section/1, section/3, article/1, article/3, aside/1, aside/3,
         header/1, header/3, footer/1, footer/3, nav/1, nav/3, main/1, main/3,
         form/1, form/3, fieldset/1, fieldset/3, legend/1, legend/3, label/1, label/3,
         strong/1, strong/3, em/1, em/3, small/1, small/3, code/1, code/3,
         pre/1, pre/3, blockquote/1, blockquote/3,
         table/1, table/3, thead/1, thead/3, tbody/1, tbody/3,
         tr/1, tr/3, th/1, th/3, td/1, td/3,
         br/0, hr/2, img/2, text/1, safe/1, fetch/3, fetch/4, on/2, on/3, preserve/0, subscribe/1, subscribe/2,
         theme_switcher/2]).
%% BEGIN GENERATED COMPONENT IMPORTS
-import(aihtml,
        [button/4,
         link_button/4,
         toggle_button/4,
         button_group/4,
         segmented_control/4,
         dropdown_button/4,
         split_button/4,
         checkbox/4,
         radiobutton/4,
         switch_button/4,
         checkbox_group/4,
         radiobutton_group/4,
         radio_cards/4,
         rating_group/4,
         input/3,
         textarea/3,
         password_input/3,
         number_input/3,
         input_otp/4,
         tag_input/3,
         dropdownlist/4,
         select/4,
         slider/4,
         field/4,
         form_layout/4,
         validate/1,
         datepicker/3,
         combobox/4,
         set_items/3,
         set_items/4,
         timepicker/3,
         colorpicker/3,
         card/3,
         panel/3,
         expander/3,
         tabs/4,
         tab_bar/4,
         breadcrumbs/3,
         pagination/4,
         steps/4,
         skeleton/2,
         loader/2,
         empty/3,
         menu/4,
         navbar/4,
         sidenav/4,
         toolbar/3,
         splitter/3,
         listmenu/4,
         status_bar/3,
         tooltip/4,
         tooltip_attrs/2,
         popover/3,
         drawer/3,
         sheet/3,
         window/3,
         notification/3,
         shows_toast/2,
         opens/1,
         toggles/1,
         closes/0,
         closes/1,
         closes/2,
         toast/3,
         avatar/3,
         badge/3,
         chip/3,
         aspect_ratio/3,
         kbd/3,
         time_ago/3,
         expandable_text/3,
         alert/3,
         progressbar/3,
         progress_circle/3,
         meter/3,
         statistic/3,
         kpi_card/3,
         timeline/3,
         ranking_list/3,
         tag_cloud/3]).
%% END GENERATED COMPONENT IMPORTS
