%% Import every aihtml builder so pages read as markup:
%%
%%   -include_lib("aihtml/include/aihtml.hrl").
%%
%%   'div'([button(<<"Save">>, save, [primary], [])], [<<"p-4">>], []).
%%
%% Leave this header out and call aihtml:button/4 etc. when an imported
%% name would clash with a local function.
%%
%% It also brings in the element records (#ah_button{} ...), see
%% aihtml_records.hrl and designs/05-records.md.
-include("aihtml_records.hrl").

-import(aihtml,
        ['div'/1, 'div'/3, span/1, span/3, p/1, p/3, a/1, a/3,
         h1/1, h1/3, h2/1, h2/3, h3/1, h3/3, h4/1, h4/3,
         ul/1, ul/3, ol/1, ol/3, li/1, li/3, dl/1, dl/3, dt/1, dt/3, dd/1, dd/3,
         section/1, section/3, article/1, article/3, aside/1, aside/3,
         header/1, header/3, footer/1, footer/3, nav/1, nav/3, main/1, main/3,
         form/1, form/3, fieldset/1, fieldset/3, legend/1, legend/3, label/1, label/3,
         strong/1, strong/3, em/1, em/3, small/1, small/3, code/1, code/3,
         pre/1, pre/3, blockquote/1, blockquote/3,
         table/1, table/3, thead/1, thead/3, tbody/1, tbody/3,
         tr/1, tr/3, th/1, th/3, td/1, td/3,
         br/0, hr/2, img/2, text/1, safe/1, fetch/3, fetch/4, on/2, on/3, preserve/0, subscribe/1, subscribe/2,
         theme_switcher/2]).
%% BEGIN GENERATED COMPONENT IMPORTS
-import(aihtml,
        [button/4,
         link_button/4,
         toggle_button/4,
         button_group/4,
         segmented_control/4,
         dropdown_button/4,
         split_button/4,
         checkbox/4,
         radiobutton/4,
         switch_button/4,
         checkbox_group/4,
         radiobutton_group/4,
         radio_cards/4,
         rating_group/4,
         input/3,
         textarea/3,
         password_input/3,
         number_input/3,
         input_otp/4,
         tag_input/3,
         markdown_editor/3,
         markdown_view/3,
         dropdownlist/4,
         select/4,
         slider/4,
         field/4,
         validate/1,
         form_layout/4,
         datepicker/3,
         combobox/4,
         set_items/3,
         set_items/4,
         timepicker/3,
         colorpicker/3,
         calendar/3,
         set_events/3,
         add_event/3,
         datetime_input/3,
         cascader/4,
         cascader_children/3,
         cascader_children/4,
         listbox/4,
         listbox_items/3,
         listbox_items/4,
         transfer/4,
         masked_input/3,
         formatted_input/3,
         range_selector/4,
         repeat_button/4,
         upload/3,
         uploaded_files/1,
         card/3,
         panel/3,
         expander/3,
         tabs/4,
         tab_bar/4,
         breadcrumbs/3,
         pagination/4,
         steps/4,
         skeleton/2,
         loader/2,
         empty/3,
         menu/4,
         navbar/4,
         sidenav/4,
         toolbar/3,
         splitter/3,
         listmenu/4,
         status_bar/3,
         scrollview/3,
         scrollbar/3,
         responsive_panel/3,
         activity_bar/4,
         navigationbar/4,
         command/3,
         set_command_items/3,
         sortable/4,
         dragdrop/3,
         draggable_attrs/2,
         drop_zone_attrs/2,
         docking/3,
         docking_add_window/4,
         dock_layout/3,
         dock_layout_open/3,
         dock_layout_open/4,
         ribbon/4,
         tile_layout/4,
         tooltip/4,
         tooltip_attrs/2,
         popover/3,
         drawer/3,
         sheet/3,
         shows_toast/2,
         toast/3,
         notification/3,
         window/3,
         avatar/3,
         badge/3,
         chip/3,
         aspect_ratio/3,
         kbd/3,
         time_ago/3,
         expandable_text/3,
         alert/3,
         progressbar/3,
         progress_circle/3,
         meter/3,
         statistic/3,
         kpi_card/3,
         timeline/3,
         ranking_list/3,
         tag_cloud/3,
         tree/4,
         set_children/3,
         nav_tree/4,
         diff/4,
         heatmap_calendar/3,
         datagrid/4,
         datagrid_query/1,
         datagrid_rows/4,
         datagrid_row/3,
         datagrid_select/2,
         pivotgrid/4,
         pivotgrid_rows/3,
         pivotgrid_view/1,
         pivotgrid_cell/1,
         treegrid/4,
         treegrid_children/3,
         datatable/4,
         datatable_query/1,
         datatable_rows/3,
         datatable_row/4,
         gantt/3,
         gantt_update/3,
         scheduler/4,
         scheduler_range/1,
         scheduler_update/3,
         swimlane/3,
         swimlane_update/3,
         chart/3,
         chart_option/1,
         chart_update/3,
         area_chart/3,
         bar_chart/3,
         donut_chart/3,
         radar_chart/3,
         relation_graph/3,
         node_graph/3,
         node_graph_layout/1,
         set_node_graph/3,
         opens/1,
         toggles/1,
         closes/0,
         closes/1,
         closes/2]).
%% END GENERATED COMPONENT IMPORTS
