%% Import every aihtml builder so pages read as markup:
%%
%%   -include_lib("aihtml/include/aihtml.hrl").
%%
%%   ah_div([ah_button(<<"Save">>, save, [primary], [])], [<<"p-4">>], []).
%%
%% Leave this header out and call aihtml:ah_button/4 etc. when an imported
%% name would clash with a local function.
%%
%% It also brings in the element records (#ah_button{} ...), see
%% aihtml_records.hrl and designs/05-records.md.
-include("aihtml_records.hrl").

-import(aihtml,
        [ah_div/1, ah_div/3, ah_span/1, ah_span/3, ah_p/1, ah_p/3, ah_a/1, ah_a/3,
         ah_h1/1, ah_h1/3, ah_h2/1, ah_h2/3, ah_h3/1, ah_h3/3, ah_h4/1, ah_h4/3,
         ah_ul/1, ah_ul/3, ah_ol/1, ah_ol/3, ah_li/1, ah_li/3,
         ah_dl/1, ah_dl/3, ah_dt/1, ah_dt/3, ah_dd/1, ah_dd/3,
         ah_section/1, ah_section/3, ah_article/1, ah_article/3, ah_aside/1, ah_aside/3,
         ah_header/1, ah_header/3, ah_footer/1, ah_footer/3,
         ah_nav/1, ah_nav/3, ah_main/1, ah_main/3,
         ah_form/1, ah_form/3, ah_fieldset/1, ah_fieldset/3,
         ah_legend/1, ah_legend/3, ah_label/1, ah_label/3,
         ah_strong/1, ah_strong/3, ah_em/1, ah_em/3, ah_small/1, ah_small/3,
         ah_code/1, ah_code/3, ah_pre/1, ah_pre/3, ah_blockquote/1, ah_blockquote/3,
         ah_table/1, ah_table/3, ah_thead/1, ah_thead/3, ah_tbody/1, ah_tbody/3,
         ah_tr/1, ah_tr/3, ah_th/1, ah_th/3, ah_td/1, ah_td/3,
         ah_br/0, ah_hr/2, ah_img/2, ah_theme_switcher/2,
         text/1, safe/1, fetch/3, fetch/4, on/2, on/3, on_client/2, preserve/0, subscribe/1, subscribe/2]).
%% BEGIN GENERATED COMPONENT IMPORTS
-import(aihtml,
        [ah_button/4,
         ah_link_button/4,
         ah_toggle_button/4,
         ah_button_group/4,
         ah_segmented_control/4,
         ah_dropdown_button/4,
         ah_split_button/4,
         ah_checkbox/4,
         ah_radiobutton/4,
         ah_switch_button/4,
         ah_checkbox_group/4,
         ah_radiobutton_group/4,
         ah_radio_cards/4,
         ah_rating_group/4,
         ah_input/3,
         ah_textarea/3,
         ah_password_input/3,
         ah_number_input/3,
         ah_input_otp/4,
         ah_tag_input/3,
         ah_markdown_editor/3,
         ah_markdown_view/3,
         ah_dropdownlist/4,
         ah_select/4,
         ah_slider/4,
         ah_field/4,
         validate/1,
         ah_form_layout/4,
         ah_datepicker/3,
         ah_combobox/4,
         set_items/3,
         set_items/4,
         ah_timepicker/3,
         ah_colorpicker/3,
         ah_calendar/3,
         set_events/3,
         add_event/3,
         ah_datetime_input/3,
         ah_cascader/4,
         cascader_children/3,
         cascader_children/4,
         ah_listbox/4,
         listbox_items/3,
         listbox_items/4,
         ah_transfer/4,
         ah_masked_input/3,
         ah_formatted_input/3,
         ah_range_selector/4,
         ah_repeat_button/4,
         ah_upload/3,
         uploaded_files/1,
         ah_card/3,
         ah_panel/3,
         ah_expander/3,
         ah_tabs/4,
         ah_tab_bar/4,
         ah_breadcrumbs/3,
         ah_pagination/4,
         ah_steps/4,
         ah_skeleton/2,
         ah_loader/2,
         ah_empty/3,
         ah_menu/4,
         ah_navbar/4,
         ah_sidenav/4,
         ah_toolbar/3,
         ah_splitter/3,
         ah_listmenu/4,
         ah_status_bar/3,
         ah_scrollview/3,
         ah_scrollbar/3,
         ah_responsive_panel/3,
         ah_activity_bar/4,
         ah_navigationbar/4,
         ah_command/3,
         set_command_items/3,
         ah_sortable/4,
         ah_dragdrop/3,
         draggable_attrs/2,
         drop_zone_attrs/2,
         ah_docking/3,
         docking_add_window/4,
         ah_dock_layout/3,
         dock_layout_open/3,
         dock_layout_open/4,
         ah_ribbon/4,
         ah_tile_layout/4,
         ah_tooltip/4,
         tooltip_attrs/2,
         ah_popover/3,
         ah_drawer/3,
         ah_sheet/3,
         shows_toast/2,
         ah_toast/3,
         ah_notification/3,
         ah_window/3,
         ah_avatar/3,
         ah_badge/3,
         ah_chip/3,
         ah_aspect_ratio/3,
         ah_kbd/3,
         ah_time_ago/3,
         ah_expandable_text/3,
         ah_alert/3,
         ah_progressbar/3,
         ah_progress_circle/3,
         ah_meter/3,
         ah_statistic/3,
         ah_kpi_card/3,
         ah_timeline/3,
         ah_ranking_list/3,
         ah_tag_cloud/3,
         ah_tree/4,
         set_children/3,
         ah_nav_tree/4,
         ah_diff/4,
         ah_heatmap_calendar/3,
         ah_datagrid/4,
         datagrid_query/1,
         datagrid_rows/4,
         datagrid_row/3,
         datagrid_select/2,
         ah_pivotgrid/4,
         pivotgrid_rows/3,
         pivotgrid_view/1,
         pivotgrid_cell/1,
         ah_treegrid/4,
         treegrid_children/3,
         ah_datatable/4,
         datatable_query/1,
         datatable_rows/3,
         datatable_row/4,
         ah_gantt/3,
         gantt_update/3,
         ah_scheduler/4,
         scheduler_range/1,
         scheduler_update/3,
         ah_swimlane/3,
         swimlane_update/3,
         ah_chart/3,
         chart_option/1,
         chart_update/3,
         ah_area_chart/3,
         ah_bar_chart/3,
         ah_donut_chart/3,
         ah_radar_chart/3,
         ah_relation_graph/3,
         ah_node_graph/3,
         node_graph_layout/1,
         set_node_graph/3,
         opens/1,
         toggles/1,
         closes/0,
         closes/1,
         closes/2]).
%% END GENERATED COMPONENT IMPORTS
