/* pagination: the page list the browser re-renders (shared template
 * pagination_items) equals what the server renders for the same state.
 * SERVER holds server renders of aihtml_pagination:pagination/4 (id "p"),
 * generated from Erlang; regenerate them if the markup changes. */
(function (T, $, AH) {
  "use strict";

  var SERVER = {
  "p1": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"1\" data-total=\"200\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:true}\"><li class=\"ah-pagination-nav ah-pagination-first-last ah-pagination-nav-disabled\" data-type=\"first\" role=\"button\" tabindex=\"-1\" aria-label=\"First\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">«</span><span class=\"ah-pagination-nav-label\">First</span></li><li class=\"ah-pagination-nav ah-pagination-nav-disabled\" data-type=\"prev\" role=\"button\" tabindex=\"-1\" aria-label=\"Previous\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"1\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 1\" aria-current=\"page\">1</li><li class=\"ah-pagination-item\" data-page=\"2\" role=\"button\" tabindex=\"0\" aria-label=\"Page 2\">2</li><li class=\"ah-pagination-item\" data-page=\"3\" role=\"button\" tabindex=\"0\" aria-label=\"Page 3\">3</li><li class=\"ah-pagination-item\" data-page=\"4\" role=\"button\" tabindex=\"0\" aria-label=\"Page 4\">4</li><li class=\"ah-pagination-item\" data-page=\"5\" role=\"button\" tabindex=\"0\" aria-label=\"Page 5\">5</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"20\" role=\"button\" tabindex=\"0\" aria-label=\"Page 20\">20</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"last\" role=\"button\" tabindex=\"0\" aria-label=\"Last\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">»</span><span class=\"ah-pagination-nav-label\">Last</span></li></ul></div>",
  "p10": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"10\" data-total=\"200\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:true}\"><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"first\" role=\"button\" tabindex=\"0\" aria-label=\"First\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">«</span><span class=\"ah-pagination-nav-label\">First</span></li><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"9\" role=\"button\" tabindex=\"0\" aria-label=\"Page 9\">9</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"10\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 10\" aria-current=\"page\">10</li><li class=\"ah-pagination-item\" data-page=\"11\" role=\"button\" tabindex=\"0\" aria-label=\"Page 11\">11</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"20\" role=\"button\" tabindex=\"0\" aria-label=\"Page 20\">20</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"last\" role=\"button\" tabindex=\"0\" aria-label=\"Last\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">»</span><span class=\"ah-pagination-nav-label\">Last</span></li></ul></div>",
  "p17": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"17\" data-total=\"200\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:true}\"><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"first\" role=\"button\" tabindex=\"0\" aria-label=\"First\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">«</span><span class=\"ah-pagination-nav-label\">First</span></li><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"16\" role=\"button\" tabindex=\"0\" aria-label=\"Page 16\">16</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"17\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 17\" aria-current=\"page\">17</li><li class=\"ah-pagination-item\" data-page=\"18\" role=\"button\" tabindex=\"0\" aria-label=\"Page 18\">18</li><li class=\"ah-pagination-item\" data-page=\"19\" role=\"button\" tabindex=\"0\" aria-label=\"Page 19\">19</li><li class=\"ah-pagination-item\" data-page=\"20\" role=\"button\" tabindex=\"0\" aria-label=\"Page 20\">20</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"last\" role=\"button\" tabindex=\"0\" aria-label=\"Last\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">»</span><span class=\"ah-pagination-nav-label\">Last</span></li></ul></div>",
  "p20": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"20\" data-total=\"200\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:true}\"><li class=\"ah-pagination-nav ah-pagination-first-last\" data-type=\"first\" role=\"button\" tabindex=\"0\" aria-label=\"First\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">«</span><span class=\"ah-pagination-nav-label\">First</span></li><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"16\" role=\"button\" tabindex=\"0\" aria-label=\"Page 16\">16</li><li class=\"ah-pagination-item\" data-page=\"17\" role=\"button\" tabindex=\"0\" aria-label=\"Page 17\">17</li><li class=\"ah-pagination-item\" data-page=\"18\" role=\"button\" tabindex=\"0\" aria-label=\"Page 18\">18</li><li class=\"ah-pagination-item\" data-page=\"19\" role=\"button\" tabindex=\"0\" aria-label=\"Page 19\">19</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"20\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 20\" aria-current=\"page\">20</li><li class=\"ah-pagination-nav ah-pagination-nav-disabled\" data-type=\"next\" role=\"button\" tabindex=\"-1\" aria-label=\"Next\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li><li class=\"ah-pagination-nav ah-pagination-first-last ah-pagination-nav-disabled\" data-type=\"last\" role=\"button\" tabindex=\"-1\" aria-label=\"Last\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">»</span><span class=\"ah-pagination-nav-label\">Last</span></li></ul></div>",
  "s1": "<div class=\"ah-pagination ah-pagination-simple\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"1\" data-total=\"95\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:true,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;&lt;b&gt;{0}&lt;/b&gt; of {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav ah-pagination-nav-disabled\" data-type=\"prev\" role=\"button\" tabindex=\"-1\" aria-label=\"Previous\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-simple-info\">&lt;b&gt;1&lt;/b&gt; of 10</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>",
  "s4": "<div class=\"ah-pagination ah-pagination-simple\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"4\" data-total=\"95\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:true,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;&lt;b&gt;{0}&lt;/b&gt; of {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-simple-info\">&lt;b&gt;4&lt;/b&gt; of 10</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>",
  "sib1": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"1\" data-total=\"300\" data-page-size=\"10\" data-max-visible=\"9\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav ah-pagination-nav-disabled\" data-type=\"prev\" role=\"button\" tabindex=\"-1\" aria-label=\"Previous\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"1\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 1\" aria-current=\"page\">1</li><li class=\"ah-pagination-item\" data-page=\"2\" role=\"button\" tabindex=\"0\" aria-label=\"Page 2\">2</li><li class=\"ah-pagination-item\" data-page=\"3\" role=\"button\" tabindex=\"0\" aria-label=\"Page 3\">3</li><li class=\"ah-pagination-item\" data-page=\"4\" role=\"button\" tabindex=\"0\" aria-label=\"Page 4\">4</li><li class=\"ah-pagination-item\" data-page=\"5\" role=\"button\" tabindex=\"0\" aria-label=\"Page 5\">5</li><li class=\"ah-pagination-item\" data-page=\"6\" role=\"button\" tabindex=\"0\" aria-label=\"Page 6\">6</li><li class=\"ah-pagination-item\" data-page=\"7\" role=\"button\" tabindex=\"0\" aria-label=\"Page 7\">7</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"30\" role=\"button\" tabindex=\"0\" aria-label=\"Page 30\">30</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>",
  "sib15": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"15\" data-total=\"300\" data-page-size=\"10\" data-max-visible=\"9\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"13\" role=\"button\" tabindex=\"0\" aria-label=\"Page 13\">13</li><li class=\"ah-pagination-item\" data-page=\"14\" role=\"button\" tabindex=\"0\" aria-label=\"Page 14\">14</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"15\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 15\" aria-current=\"page\">15</li><li class=\"ah-pagination-item\" data-page=\"16\" role=\"button\" tabindex=\"0\" aria-label=\"Page 16\">16</li><li class=\"ah-pagination-item\" data-page=\"17\" role=\"button\" tabindex=\"0\" aria-label=\"Page 17\">17</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"30\" role=\"button\" tabindex=\"0\" aria-label=\"Page 30\">30</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>",
  "t200": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"3\" data-total=\"200\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-item\" data-page=\"2\" role=\"button\" tabindex=\"0\" aria-label=\"Page 2\">2</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"3\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 3\" aria-current=\"page\">3</li><li class=\"ah-pagination-item\" data-page=\"4\" role=\"button\" tabindex=\"0\" aria-label=\"Page 4\">4</li><li class=\"ah-pagination-item\" data-page=\"5\" role=\"button\" tabindex=\"0\" aria-label=\"Page 5\">5</li><li class=\"ah-pagination-ellipsis\" aria-hidden=\"true\">…</li><li class=\"ah-pagination-item\" data-page=\"20\" role=\"button\" tabindex=\"0\" aria-label=\"Page 20\">20</li><li class=\"ah-pagination-nav\" data-type=\"next\" role=\"button\" tabindex=\"0\" aria-label=\"Next\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>",
  "t25": "<div class=\"ah-pagination\" role=\"navigation\" aria-label=\"Pagination\" data-ah=\"pagination\" data-ah-value=\"3\" data-total=\"25\" data-page-size=\"10\" data-max-visible=\"7\" id=\"p\"><ul class=\"ah-pagination-pages\" data-view=\"{&quot;simple&quot;:false,&quot;labels&quot;:{&quot;first&quot;:&quot;First&quot;,&quot;last&quot;:&quot;Last&quot;,&quot;next&quot;:&quot;Next&quot;,&quot;prev&quot;:&quot;Previous&quot;,&quot;page_info&quot;:&quot;Page {0} / {1}&quot;},&quot;href&quot;:null,&quot;first_last&quot;:false}\"><li class=\"ah-pagination-nav\" data-type=\"prev\" role=\"button\" tabindex=\"0\" aria-label=\"Previous\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">‹</span><span class=\"ah-pagination-nav-label\">Previous</span></li><li class=\"ah-pagination-item\" data-page=\"1\" role=\"button\" tabindex=\"0\" aria-label=\"Page 1\">1</li><li class=\"ah-pagination-item\" data-page=\"2\" role=\"button\" tabindex=\"0\" aria-label=\"Page 2\">2</li><li class=\"ah-pagination-item ah-pagination-item-active\" data-page=\"3\" role=\"button\" tabindex=\"-1\" aria-label=\"Page 3\" aria-current=\"page\">3</li><li class=\"ah-pagination-nav ah-pagination-nav-disabled\" data-type=\"next\" role=\"button\" tabindex=\"-1\" aria-label=\"Next\" aria-disabled=\"true\"><span class=\"ah-pagination-nav-icon\" aria-hidden=\"true\">›</span><span class=\"ah-pagination-nav-label\">Next</span></li></ul></div>"
};

  // Markup with attributes and class tokens sorted, so that the order in
  // which jQuery adds them does not matter.
  function norm(node) {
    if (node.nodeType === 3) { return node.nodeValue; }
    var attrs = Array.prototype.map.call(node.attributes, function (a) {
      var v = a.name === "class" ? a.value.split(/\s+/).filter(Boolean).sort().join(" ") : a.value;
      return a.name + "=" + JSON.stringify(v);
    }).sort();
    return "<" + node.tagName.toLowerCase() + " " + attrs.join(" ") + ">" +
      Array.prototype.map.call(node.childNodes, norm).join("") + "</" + node.tagName.toLowerCase() + ">";
  }

  function server(name, sel) {
    var d = document.createElement("div");
    d.innerHTML = SERVER[name];
    return norm(d.querySelector(sel));
  }

  function mount(fx, name) {
    fx.innerHTML = SERVER[name];
    AH.mount(fx);
    return fx.firstChild;
  }

  function samePages(el, name) {
    T.eq(norm(el.querySelector(".ah-pagination-pages")), server(name, ".ah-pagination-pages"), name);
    T.eq(el.getAttribute("data-ah-value"), $(SERVER[name]).attr("data-ah-value"), name + " value");
  }

  T.test("pagination: setPage re-renders the list as the server does", function (fx) {
    var el = mount(fx, "p1");
    samePages(el, "p1");
    [["p10", 10], ["p17", 17], ["p20", 20], ["p1", 1]].forEach(function (c) {
      AH.invoke(el, "setPage", c[1]);
      samePages(el, c[0]);
    });
  });

  T.test("pagination: clicks and siblings give the server list", function (fx) {
    var el = mount(fx, "sib1");
    AH.invoke(el, "setPage", 15);
    samePages(el, "sib15");
    AH.invoke(el, "first");
    samePages(el, "sib1");
  });

  T.test("pagination: simple mode info text (escaped label)", function (fx) {
    var el = mount(fx, "s1");
    var changed = 0;
    $(el).on("change", function () { changed++; });
    $(el).find("[data-type=next]").trigger("click").end();
    $(el).find("[data-type=next]").trigger("click");
    $(el).find("[data-type=next]").trigger("click");
    samePages(el, "s4");
    T.eq(changed, 3);
  });

  T.test("pagination: setTotal clamps the page and re-renders", function (fx) {
    var el = mount(fx, "t200");
    AH.invoke(el, "setTotal", 25);
    samePages(el, "t25");
  });
})(window.AHTest, window.jQuery, window.AH);
